// AUTO-GENERATED by convert_to_mdx.py. Do not edit by hand.
export const bookMeta = {
  "mark": "✠",
  "title": "Christ Is God",
  "subtitle": "The Divinity of Christ",
  "tagline": "A Scriptural, Historical, and Grammatical Case for the Deity of Jesus Christ",
  "year": "2026",
  "epigraphs": [
    {
      "text": "I and the Father are one.",
      "ref": "John 10:30"
    },
    {
      "text": "For in him dwelleth all the fulness of the Godhead bodily.",
      "ref": "Colossians 2:9"
    }
  ]
} as const;
