// AUTO-GENERATED by convert_to_mdx.py. Do not edit by hand.
import type { ComponentType } from "react";

export type Chapter = {
  slug: string;
  order: number;
  numeral: string | null;
  title: string;
  subtitle: string | null;
  load: () => Promise<{ default: ComponentType }>;
};

export const chapters: Chapter[] = [
  {
    slug: "i-introduction",
    order: 0,
    numeral: "I",
    title: "Introduction",
    subtitle: "Why the Divinity of Christ Matters",
    load: () => import("@/content/00-i-introduction.mdx"),
  },
  {
    slug: "ii-the-monotheistic-context",
    order: 1,
    numeral: "II",
    title: "The Monotheistic Context",
    subtitle: "Why the Claim Was Radical",
    load: () => import("@/content/01-ii-the-monotheistic-context.mdx"),
  },
  {
    slug: "iii-romans-95",
    order: 2,
    numeral: "III",
    title: "Romans 9:5",
    subtitle: "The Anchor Text",
    load: () => import("@/content/02-iii-romans-95.mdx"),
  },
  {
    slug: "iv-jesus-is-god",
    order: 3,
    numeral: "IV",
    title: "“Jesus Is God”",
    subtitle: "The Direct Witness of Scripture",
    load: () => import("@/content/03-iv-jesus-is-god.mdx"),
  },
  {
    slug: "v-old-testament-theophanies",
    order: 4,
    numeral: "V",
    title: "Old Testament Theophanies",
    subtitle: "The Angel of the LORD",
    load: () => import("@/content/04-v-old-testament-theophanies.mdx"),
  },
  {
    slug: "vi-the-divine-works-of-christ",
    order: 5,
    numeral: "VI",
    title: "The Divine Works of Christ",
    subtitle: null,
    load: () => import("@/content/05-vi-the-divine-works-of-christ.mdx"),
  },
  {
    slug: "vii-the-indirect-but-unmistakable-claim",
    order: 6,
    numeral: "VII",
    title: "The Indirect but Unmistakable Claim",
    subtitle: null,
    load: () => import("@/content/06-vii-the-indirect-but-unmistakable-claim.mdx"),
  },
  {
    slug: "viii-worship-given-to-christ",
    order: 7,
    numeral: "VIII",
    title: "Worship Given to Christ",
    subtitle: null,
    load: () => import("@/content/07-viii-worship-given-to-christ.mdx"),
  },
  {
    slug: "ix-the-omnipresence-of-christ",
    order: 8,
    numeral: "IX",
    title: "The Omnipresence of Christ",
    subtitle: null,
    load: () => import("@/content/08-ix-the-omnipresence-of-christ.mdx"),
  },
  {
    slug: "x-the-holy-trinity",
    order: 9,
    numeral: "X",
    title: "The Holy Trinity",
    subtitle: "A Comparative Table",
    load: () => import("@/content/09-x-the-holy-trinity.mdx"),
  },
  {
    slug: "xi-how-early-is-this-belief",
    order: 10,
    numeral: "XI",
    title: "How Early Is This Belief?",
    subtitle: "The Antiquity of the Confession",
    load: () => import("@/content/10-xi-how-early-is-this-belief.mdx"),
  },
  {
    slug: "xii-the-manuscript-and-textual-witness",
    order: 11,
    numeral: "XII",
    title: "The Manuscript and Textual Witness",
    subtitle: null,
    load: () => import("@/content/11-xii-the-manuscript-and-textual-witness.mdx"),
  },
  {
    slug: "xiii-islams-view-of-christ",
    order: 12,
    numeral: "XIII",
    title: "Islam's View of Christ",
    subtitle: null,
    load: () => import("@/content/12-xiii-islams-view-of-christ.mdx"),
  },
  {
    slug: "xiv-anticipating-objections",
    order: 13,
    numeral: "XIV",
    title: "Anticipating Objections",
    subtitle: null,
    load: () => import("@/content/13-xiv-anticipating-objections.mdx"),
  },
  {
    slug: "xv-a-compact-apologetic-case",
    order: 14,
    numeral: "XV",
    title: "A Compact Apologetic Case",
    subtitle: null,
    load: () => import("@/content/14-xv-a-compact-apologetic-case.mdx"),
  },
  {
    slug: "xvi-conclusion",
    order: 15,
    numeral: "XVI",
    title: "Conclusion",
    subtitle: "From Confession to Worship",
    load: () => import("@/content/15-xvi-conclusion.mdx"),
  },
  {
    slug: "sources-consulted",
    order: 16,
    numeral: null,
    title: "Sources Consulted",
    subtitle: null,
    load: () => import("@/content/16-sources-consulted.mdx"),
  },
];

export const chapterBySlug = (slug: string) =>
  chapters.find((c) => c.slug === slug);
